# basic julia codes
# https://www.youtube.com/watch?v=iYdM9ojrsIE&list=PLdPQZLMHRjDJ5d_dE4FeOviv0gRe4UYsB&index=4&ab_channel=umrobotics

In [ ]:
import Pkg
Pkg.add("Plots")

In [ ]:
using Plots

In [ ]:
f(x) = x + 3

plot(f, -5, 5)

In [ ]:
# Solve 2x - y = -1, 4x + y = 4
# Re-arranging both eqs and keeping y on left

y1(x) = 2x + 1
y2(x) = 4 - 4x
plot([y1,y2], -5, 5, xlabel = "x", ylabel = "y")

In [ ]:
rowVect = [1 2 3 4 5]
# rowVect1 = collect(1:10)'
prink = collect(0:2:8)

In [ ]:
# creating matrices
onesMat = ones(3,4)

In [ ]:
@assert sum(onesMat) == 12

In [ ]:
zeroMat = zeros(2,1)
# zeroMat1 = 7*ones(2,2)

In [ ]:
A = [1 5 0; 3 -1 7; -1 0 2]

In [ ]:
b = [4; 2; -5]

In [ ]:
using Pkg
Pkg.add("LinearAlgebra")
using LinearAlgebra

In [ ]:
det(A)

In [ ]:
B = [1 1 2 0 0; 2 -1 1 0 0; 1 0 4 0 0; 0 0 2 1 -5; 0 -4 0 12 0]

In [ ]:
det(B)

In [ ]:
row_vec = [1 3 5 7 9]
almost_zero_vec = [0; 0; -pi; 0; 0; 0; 0]
using Random
Random.seed!(1234)
rand_mat = rand(3, 4)

In [ ]:
num = almost_zero_vec[3] # index into matrices using SQUARE BRACKETS
num1 = rand_mat[2, 1] # 2nd row 1st column entry of rand_mat
num2 = rand_mat[:, 3] # selects all rows and 3rd column

In [ ]:
row_vec = rand_mat[1:1, :] # gives row matrix
row_vec1 = rand_mat[1:1, 1:end] # same results as above
col1 = [0; 0; -pi; 0; 0; 0; 0]'

In [ ]:
A1 = [1 5 0; 3 -1 7; -1 0 2]
block_A1 = A1[1:2, 1:2] # takes out the block of elements from A1
block1_A1 = A1[2:3, 2:3]
num3 = block1_A1[2,2]
res = pi/num3


In [7]:
A3 = [1 8 2; 0 3 7; 6 2 9]
# sums = A3[1, 1] + A3[2, 2] + A3[3, 3]

3×3 Matrix{Int64}:
 1  8  2
 0  3  7
 6  2  9

In [ ]:
for mynum in 1:10 # i is the iterator or dummy variable
    println("Hi")
end

In [ ]:
for k = 20:-2:2 # step size can be negative
    println(k)
end

In [ ]:
using Random
Random.seed!(1234)
rand1 = rand(30,30)

In [ ]:
sums = 0
for k = 1:30
    # sums = sums + rand1[k,k]
    sums += rand1[k,k]
end
println(sums)

In [6]:
# print all the numbers below and up of diagonals
for i = 1:3
    for j = 1:i
        println(A3[i,j])
    end
end

1
0
3
6
2
9


In [14]:
using Random
Random.seed!(1234)
mat1 = rand(10,10)

10×10 Matrix{Float64}:
 0.579862   0.566704  0.526344   0.00543656  …  0.829076  0.587688  0.850302
 0.411294   0.536369  0.0779683  0.698478       0.892646  0.381363  0.124847
 0.972136   0.711389  0.966197   0.349231       0.806471  0.42562   0.993609
 0.0149088  0.103929  0.666558   0.91097        0.011625  0.661096  0.0686571
 0.520355   0.806704  0.333859   0.973653       0.249676  0.195737  0.953362
 0.639562   0.870539  0.802199   0.76066     …  0.139687  0.811324  0.484337
 0.839622   0.962715  0.156458   0.488912       0.180998  0.594965  0.131026
 0.967143   0.15118   0.380799   0.362643       0.813512  0.270995  0.946453
 0.789764   0.715355  0.0687591  0.708738       0.994935  0.566878  0.574323
 0.696041   0.939548  0.861725   0.656694       0.77916   0.607905  0.67765

In [16]:
# sum of primary diagonal elements of matrix mat1
# that means we have to add mat1[1,1] + mat1[2,2] + mat1[3,3]
# using for loop
sum1 = 0
for row1 = 1:10
    for col1 = row1
        # println(A3[row1, col1])
        sum1 += mat1[row1, col1]
        
    end
end
println(sum1)


6.84133867975218

In [20]:
# solving system of linear equations
A = [1 3 6; 0 6 1; 7 8 2]
b = [-2; 11; 6.4]
using LinearAlgebra
x = inv(A)*b


3-element Vector{Float64}:
 -1.0696035242290747
  2.028193832599119
 -1.1691629955947136

# the determinant of a square lower/upper triangular matrix is equal to the product of the elements on the diagonal.
# the determinant of a matrix is product of its eigen values
# eigen values of the lower triangular matrix are the diagonal entries
# back substition for upper triangular matrix - forward substitution for lower triangular matrix

In [1]:
using LinearAlgebra
K1 = [3 0 0; 2 -1 0; 1 -2 3]
diag(K1)
det(K1)

3-element Vector{Int64}:
  3
 -1
  3

In [3]:
a_row = [2 -3 -1 11] # vector multiplication
b_row = [3; 5; -1; -2]
a_row * b_row

1-element Vector{Int64}:
 -30

In [ ]:
a1 = [1 2; 3 4]
a2 = [5; 6]
a1 * a2

In [13]:
# permutation matrix helps re-arrange/swap rows of a matrix
A0 = [3. 0 0; 1 -2 3; 2 -1 0] # original matrix
#b0 = [6.; 2; -2] # original right hand side
#P = [1 0 0; 0 0 1; 0 1 0] # permutation matrix

3×3 Matrix{Float64}:
 3.0   0.0  0.0
 1.0  -2.0  3.0
 2.0  -1.0  0.0

In [ ]:
AL = P * A0 # using permutation matrix to swap rows
bL = P * b0 # 2nd and 3rd row changed

In [16]:
v = [1; 2; 3; 4; 5]
P = [1 0 0 0 0; 0 1 0 0 0; 0 0 0 0 1; 0 0 0 1 0; 0 0 1 0 0]
# permute v
P * v

5-element Vector{Int64}:
 1
 2
 5
 4
 3

In [17]:
matrix1 = rand(3,4)
matrix2 = rand(4,4)
pr = matrix1 * matrix2

3×4 Matrix{Float64}:
 0.414547  0.203437  0.320534  0.394593
 1.1923    0.402149  0.846146  1.5541
 1.60205   0.717673  1.2422    1.45352